-- Criação de banco de dados SALA_DE_AULA
CREATE DATABASE SALA_DE_AULA;
GO

-- Colocar banco SALA_DE_AULA em uso
USE SALA_DE_AULA

--Criação da tabela TB_ALUNO
GO
CREATE TABLE TB_ALUNO
(	COD_ALUNO			INT,
	NOME				VARCHAR(30),
	DATA_NASCIMENTO		DATETIME,
	IDADE				TINYINT,
	E_MAIL				VARCHAR(50),
	FONE_RES			CHAR(9),
	FONE_COM			CHAR(9),
	FAX					CHAR(9),
	CELULAR				CHAR(9),
	PROFISSAO			VARCHAR(40),
	EMPRESA				VARCHAR(50) );

GO

--Campo autonumerável (IDENTITY)

DROP TABLE TB_ALUNO;		--Caso a tabela já exista
GO

CREATE TABLE TB_ALUNO
(	NUM_ALUNO			INT IDENTITY,
	NOME				VARCHAR(30),
	DATA_NASCIMENTO		DATETIME,
	IDADE				TINYINT,
	E_MAIL				VARCHAR(50),
	FONE_RES			CHAR(8),
	FONE_COM			CHAR(8),
	FAX					CHAR(8),
	CELULAR				CHAR(9),
	PROFISSAO			VARCHAR(40),
	EMPRESA				VARCHAR(50) );
GO

-- Nulabilidade
DROP TABLE TB_ALUNO;		--Caso a tabela já exista
GO

CREATE TABLE TB_ALUNO
(	CODIGO			INT			NOT NULL,
	NOME			VARCHAR(30)	NOT NULL,
	E_MAIL			VARCHAR(100)	NULL 	);

GO






  

 












-- Criando as constraints com ALTER TABLE
ALTER TABLE TB_PRODUTO ADD
    CONSTRAINT PK_TB_PRODUTO PRIMARY KEY( ID_PRODUTO );

ALTER TABLE TB_PRODUTO ADD
    CONSTRAINT UQ_TB_PRODUTO_DESCRICAO UNIQUE( DESCRICAO );

-- Criando várias constraints em um único ALTER TABLE
ALTER TABLE TB_PRODUTO ADD    
    CONSTRAINT CK_TB_PRODUTO_PRECOS 
               CHECK( PRECO_VENDA >= PRECO_CUSTO ),
    CONSTRAINT CK_TB_PRODUTO_DATA_CAD
               CHECK( DATA_CADASTRO <= GETDATE() ),
    CONSTRAINT CK_TB_PRODUTO_SN_ATIVO
               CHECK( SN_ATIVO IN ('N','S') ),
    CONSTRAINT FK_TB_PRODUTO_TIPO_PRODUTO
               FOREIGN KEY (COD_TIPO)
               REFERENCES TB_TIPO_PRODUTO (COD_TIPO),    
   CONSTRAINT DF_TB_PRODUTO_SN_ATIVO DEFAULT ('S') FOR SN_ATIVO,
   CONSTRAINT DF_TB_PRODUTO_DATA_CADASTRO DEFAULT (GETDATE())
                               FOR DATA_CADASTRO;

---1.6.3.3.	Criando constraints graficamente

USE TESTE_CONSTRAINT;

DROP TABLE TB_PRODUTO 
GO
DROP TABLE TB_TIPO_PRODUTO
GO
-- Criação da tabela TIPO_PRODUTO
CREATE TABLE TB_TIPO_PRODUTO
(	COD_TIPO			INT IDENTITY NOT NULL,
	TIPO				VARCHAR(30) NOT NULL );

-- Criando a tabela PRODUTO
CREATE TABLE TB_PRODUTOS
(   ID_PRODUTO			INT IDENTITY NOT NULL,
    DESCRICAO			VARCHAR(50),
    COD_TIPO			INT,
    PRECO_CUSTO			NUMERIC(10,2),
    PRECO_VENDA			NUMERIC(10,2),
    QTD_REAL			NUMERIC(10,2),
    QTD_MINIMA			NUMERIC(10,2),
    DATA_CADASTRO		DATETIME,
    SN_ATIVO			CHAR(1) );




