-- Usar banco de dados PEDIDOS
USE PEDIDOS;
SELECT * FROM TB_CLIENTE
WHERE EXISTS (SELECT * FROM TB_PEDIDO
    WHERE CODCLI = TB_CLIENTE.CODCLI AND
          DATA_EMISSAO BETWEEN '2014.1.1' AND '2014.1.31');  
-- OU
SELECT * FROM TB_CLIENTE
WHERE CODCLI IN (SELECT CODCLI FROM TB_PEDIDO
     WHERE DATA_EMISSAO BETWEEN '2014.1.1' AND '2014.1.31');

--No próximo exemplo, é verificada a existência de clientes que não compraram em janeiro de 2014:

SELECT * FROM TB_CLIENTE
WHERE NOT EXISTS (SELECT * FROM TB_PEDIDO
   WHERE CODCLI = TB_CLIENTE.CODCLI AND
         DATA_EMISSAO BETWEEN '2014.1.1' AND '2014.1.31');   
-- OU
SELECT * FROM TB_CLIENTE
WHERE CODCLI NOT IN (SELECT CODCLI FROM TB_PEDIDO
   WHERE DATA_EMISSAO BETWEEN '2014.1.1' AND '2014.1.31');   

 -- Exemplo 1

-- Lista de empregados cujo cargo tenha salário inicial
-- inferior a 5000                    
SELECT * FROM TB_EMPREGADO
WHERE COD_CARGO IN (SELECT COD_CARGO FROM TB_CARGO
                    WHERE SALARIO_INIC < 5000);



-- Exemplo 2

-- Lista de departamentos em que não existe nenhum
-- funcionário cadastrado
SELECT * FROM TB_DEPARTAMENTO
WHERE COD_DEPTO NOT IN 
    (SELECT DISTINCT COD_DEPTO FROM TB_EMPREGADO
     WHERE COD_DEPTO IS NOT NULL)
-- O mesmo que
SELECT  
  E.CODFUN, E.NOME, E.COD_DEPTO, E.COD_CARGO, D.COD_DEPTO, D.DEPTO
FROM TB_EMPREGADO E RIGHT JOIN TB_DEPARTAMENTO D ON E.COD_DEPTO = D.COD_DEPTO  
WHERE E.COD_DEPTO IS NULL

-- Exemplo 3

-- Lista de cargos em que não existe nenhum
-- funcionário cadastrado
SELECT * FROM TB_CARGO
WHERE COD_CARGO NOT IN 
(SELECT DISTINCT COD_CARGO FROM TB_EMPREGADO
 WHERE COD_CARGO IS NOT NULL)
-- O mesmo que
SELECT  
   C.COD_CARGO, C.CARGO
FROM TB_EMPREGADO E RIGHT JOIN TB_CARGO C ON E.COD_CARGO = C.COD_CARGO  
WHERE E.COD_CARGO IS NULL


--	Exemplo 1
-- Funcionário(s) que ganha(m) menos
SELECT * FROM TB_EMPREGADO
WHERE SALARIO = (SELECT MIN(SALARIO) FROM TB_EMPREGADO)
-- o mesmo que
SELECT TOP 1 WITH TIES * FROM TB_EMPREGADO
WHERE SALARIO IS NOT NULL
ORDER BY SALARIO

-- 	Exemplo 2

-- Funcionário mais novo na empresa
SELECT * FROM TB_EMPREGADO
WHERE DATA_ADMISSAO = 
(SELECT MAX(DATA_ADMISSAO) FROM TB_EMPREGADO);

-- O mesmo que
SELECT TOP 1 WITH TIES * FROM TB_EMPREGADO
ORDER BY DATA_ADMISSAO DESC;

UPDATE TB_EMPREGADO SET SALARIO = (SELECT SALARIO_INIC 
FROM TB_CARGO
WHERE COD_CARGO = TB_EMPREGADO.COD_CARGO);

SELECT * FROM TB_CLIENTE
WHERE NOT EXISTS (SELECT * FROM TB_PEDIDO
    WHERE CODCLI = TB_CLIENTE.CODCLI AND
          DATA_EMISSAO BETWEEN '2014.1.1' AND '2014.1.31');   

SELECT P.CODVEN, V.NOME,
  SUM(P.VLR_TOTAL) AS TOT_VENDIDO,
  100 * SUM(P.VLR_TOTAL) / (SELECT SUM(VLR_TOTAL) 
FROM TB_PEDIDO
     WHERE DATA_EMISSAO BETWEEN '2014.1.1' AND  '2014.1.31') AS PORCENTAGEM
FROM TB_PEDIDO P JOIN TB_VENDEDOR V ON P.CODVEN = V.CODVEN  
WHERE P.DATA_EMISSAO BETWEEN '2014.1.1' AND '2014.1.31'
GROUP BY P.CODVEN, V.NOME;


SELECT COD_DEPTO,
 (SELECT SUM(E.SALARIO) FROM TB_EMPREGADO E
  WHERE E.SINDICALIZADO = 'S' AND 
        E.COD_DEPTO = TB_EMPREGADO.COD_DEPTO) AS TOT_SALARIO_SIND,
 (SELECT SUM(E.SALARIO) FROM TB_EMPREGADO E
  WHERE E.SINDICALIZADO = 'N' AND 
        E.COD_DEPTO = TB_EMPREGADO.COD_DEPTO) AS TOT_SALARIO_NAO_SIND
FROM TB_EMPREGADO
GROUP BY COD_DEPTO;

SELECT * FROM TB_PEDIDO
WHERE CODVEN IN (SELECT CODVEN FROM TB_VENDEDOR WHERE NOME = 'LEIA')
AND CODCLI IN (        
                SELECT CODCLI FROM TB_CLIENTE
                WHERE CODCLI NOT IN (SELECT CODCLI FROM TB_PEDIDO
                                     WHERE DATA_EMISSAO BETWEEN 
                                    '2014.1.1' AND '2014.1.31') AND
                      CODCLI IN (SELECT CODCLI FROM TB_PEDIDO
                                 WHERE DATA_EMISSAO BETWEEN '2013.12.1' 
                                       AND '2013.12.31') 
                AND ESTADO = 'SP' );

-- Tabela temporária 1 - Código da vendedora LEIA
SELECT CODVEN INTO #VEND_LEIA FROM TB_VENDEDOR WHERE NOME = 'LEIA';             

-- Tabela temporária 2 - Clientes que compraram em Jan/2014
SELECT CODCLI INTO #CLI_COM_PED_JAN_2014 FROM TB_PEDIDO 
WHERE DATA_EMISSAO BETWEEN '2014.1.1' AND '2014.1.31';

-- Tabela temporária 3 - Clientes que compraram em Dez/2013
SELECT CODCLI INTO #CLI_COM_PED_DEZ_2013 FROM TB_PEDIDO 
WHERE DATA_EMISSAO BETWEEN '2013.12.1' AND '2013.12.31';

-- Tabela temporária 4 - Clientes de SP que compraram
-- em Dez/2013, mas não compraram em Jan de 2014
SELECT CODCLI INTO #CLI_FINAL FROM TB_CLIENTE
WHERE CODCLI NOT IN (SELECT CODCLI FROM #CLI_COM_PED_JAN_2014)
      AND
      CODCLI IN (SELECT CODCLI FROM #CLI_COM_PED_DEZ_2013) 
      AND 
      ESTADO = 'SP'; 

-- SELECT de TB_PEDIDO
SELECT * FROM TB_PEDIDO
WHERE CODVEN IN (SELECT CODVEN FROM #VEND_LEIA)
      AND
      CODCLI IN (SELECT CODCLI FROM #CLI_FINAL);  
