USE PEDIDOS


UPDATE TB_EMPREGADO
SET SALARIO = SALARIO * 1.10
WHERE COD_DEPTO = (SELECT COD_DEPTO FROM TB_DEPARTAMENTO
                   WHERE DEPTO = 'CPD');

UPDATE TB_PRODUTO SET PRECO_VENDA = PRECO_CUSTO * 1.2
WHERE COD_TIPO = (SELECT COD_TIPO FROM TB_TIPOPRODUTO
                  WHERE TIPO = 'REGUA');


DELETE FROM TB_PEDIDO
WHERE DATA_EMISSAO BETWEEN '2013.12.1' AND '2013.12.15' AND
      CODVEN = (SELECT CODVEN FROM TB_VENDEDOR WHERE NOME = 'MARCELO');


UPDATE TB_EMPREGADO
SET SALARIO *= 1.10
FROM TB_EMPREGADO E JOIN TB_DEPARTAMENTO D ON E.COD_DEPTO = D.COD_DEPTO
WHERE D.DEPTO = 'CPD';

UPDATE TB_PRODUTO SET PRECO_VENDA = PRECO_CUSTO * 1.2
FROM TB_PRODUTO P JOIN TB_TIPOPRODUTO T ON P.COD_TIPO = T.COD_TIPO
WHERE T.TIPO = 'REGUA';


DELETE FROM TB_PEDIDO
FROM TB_PEDIDO P JOIN TB_VENDEDOR V ON P.CODVEN = V.CODVEN
WHERE P.DATA_EMISSAO BETWEEN '2013.12.1' AND '2013.12.15' AND
      V.NOME = 'MARCELO';
