--Caso a tabela não tenha sido criada
CREATE TABLE TB_ALUNO
(	COD_ALUNO			INT IDENTITY PRIMARY KEY,
	NOME				VARCHAR(30),
	DATA_NASCIMENTO		DATETIME,
	IDADE				TINYINT,
	E_MAIL				VARCHAR(50),
	FONE_RES			CHAR(9),
	FONE_COM			CHAR(9),
	FAX					CHAR(9),
	CELULAR				CHAR(9),
	PROFISSAO			VARCHAR(40),
	EMPRESA				VARCHAR(50) );
go

INSERT INTO TB_ALUNO
(NOME, DATA_NASCIMENTO, IDADE, E_MAIL, FONE_RES, FONE_COM, FAX,
 CELULAR, PROFISSAO, EMPRESA )
VALUES
('CARLOS MAGNO', '1959.11.12', 53, 'magno@magno.com', 
 '23456789','23459876','', '998765432',
 'ANALISTA DE SISTEMAS', 'IMPACTA TECNOLOGIA');

-- Consultar os dados inseridos na tabela
SELECT * FROM TB_ALUNO;



INSERT INTO TB_ALUNO
(NOME, DATA_NASCIMENTO, IDADE, E_MAIL, 
FONE_RES, FONE_COM, FAX, CELULAR, PROFISSAO, EMPRESA)
VALUES
('André da Silva', '1980.1.2', 33, 'andre@silva.com', 
 '23456789','23459876','', '998765432',
 'ANALISTA DE SISTEMAS', 'SOMA INFORMÁTICA'),
 ('Marcelo Soares', '1983.4.21', 30, 'marcelo@soares.com', 
 '23456789','23459876','', '998765432',
 'INSTRUTOR', 'IMPACTA TECNOLOGIA');

-- Consultar os dados da tabela
SELECT * FROM TB_ALUNO;



CREATE TABLE ALUNOS2
 (	NUM_ALUNO			INT,
	NOME				VARCHAR(30),
	DATA_NASCIMENTO		DATETIME,
	IDADE				TINYINT,
	E_MAIL			VARCHAR(50),
	FONE_RES			CHAR(8),
	FONE_COM			CHAR(8),
	FAX				CHAR(8),
	CELULAR			CHAR(9),
PROFISSAO			VARCHAR(40),
EMPRESA			VARCHAR(50) );

INSERT INTO ALUNOS2
SELECT * FROM TB_ALUNO;


INSERT INTO TB_ALUNO
VALUES
('MARIA LUIZA', '1997.10.29', 15, 'luiza@luiza.com', 
 '23456789','23459876','', '998765432',
 'ESTUDANTE', 'COLÉGIO MONTE VIDEL');
 
 -- Consultando os dados
SELECT * FROM TB_ALUNO;

INSERT INTO TB_ALUNO
(NOME, DATA_NASCIMENTO, IDADE, E_MAIL, 
 FONE_RES, FONE_COM, FAX, CELULAR, 
 PROFISSAO, EMPRESA )
VALUES
('PEDRO PAULO', '1994.2.5', 19, 'pedro@pedro.com', 
 '23456789','23459876','', '998765432',
 'ESTUDANTE', 'COLÉGIO MONTE VIDEL');

-- Consultando os dados
SELECT * FROM TB_ALUNO;



-- Colocar o banco de dados PEDIDOS em uso
USE PEDIDOS;

-- Criar a tabela
CREATE TABLE CLIENTES_MG
( CODIGO		INT		PRIMARY KEY,
  NOME			VARCHAR(50),
  ENDERECO		VARCHAR(60),
  BAIRRO		VARCHAR(30),
  CIDADE		VARCHAR(30),
  FONE			VARCHAR(18) )

-- Copiar 20 registros da tabela TB_CLIENTE
-- para a tabela CLIENTES_MG  
INSERT TOP( 20 ) INTO CLIENTES_MG
SELECT CODCLI, NOME, ENDERECO, BAIRRO, CIDADE, FONE1
FROM TB_CLIENTE
WHERE ESTADO = 'MG'

-- Consultar CLIENTES_MG
SELECT * FROM CLIENTES_MG


IF OBJECT_ID('EMP_TEMP','U') IS NOT NULL
   DROP TABLE EMP_TEMP;

CREATE TABLE EMP_TEMP
( CODFUN    INT PRIMARY KEY,
  NOME      VARCHAR(30),
  COD_DEPTO INT,
  COD_CARGO	INT,
  SALARIO	NUMERIC(10,2) );


INSERT INTO EMP_TEMP OUTPUT INSERTED.*
SELECT CODFUN, NOME, COD_DEPTO, COD_CARGO, SALARIO
FROM TB_EMPREGADO;
GO

DELETE FROM EMP_TEMP;

INSERT INTO EMP_TEMP 
OUTPUT INSERTED.CODFUN, INSERTED.NOME, INSERTED.COD_DEPTO
SELECT CODFUN, NOME, COD_DEPTO, COD_CARGO, SALARIO
FROM TB_EMPREGADO WHERE COD_DEPTO = 2;
GO

-- Declarar variável tabular
DECLARE @REG_INSERT TABLE ( 	CODFUN    INT,
					NOME      VARCHAR(30),
					COD_DEPTO INT,
					COD_CARGO	INT,
					SALARIO	NUMERIC(10,2) );

-- Inserir dados e armazenar em variável tabular
INSERT INTO EMP_TEMP 
OUTPUT INSERTED.* INTO @REG_INSERT
SELECT CODFUN, NOME, COD_DEPTO, COD_CARGO, SALARIO
FROM TB_EMPREGADO WHERE COD_DEPTO = 3;

--Para exibir os registros inseridos, utilizamos a seguinte instrução:

SELECT * FROM @REG_INSERT;

SELECT * FROM EMP_TEMP;
GO
